# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ollama_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QFileInfo

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("VirtualTA")
        MainWindow.resize(1057, 799)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Input_area = QtWidgets.QTextEdit(self.centralwidget)
        self.Input_area.setGeometry(QtCore.QRect(10, 670, 891, 81))
        self.Input_area.setObjectName("Input_area")
        self.Button_sent = QtWidgets.QPushButton(self.centralwidget)
        self.Button_sent.setGeometry(QtCore.QRect(942, 690, 101, 51))
        self.Button_sent.setObjectName("Button_sent")
        self.Chat = QtWidgets.QTextBrowser(self.centralwidget)
        self.Chat.setGeometry(QtCore.QRect(10, 21, 881, 631))
        self.Chat.setObjectName("Chat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #絕對路徑載入icon
        root = QFileInfo(__file__).absolutePath()
        MainWindow.setWindowIcon(QtGui.QIcon(root+'/VirtualTA.ico'))
        #工作列icon綁定
        import ctypes
        myappid = 'mycompany.myproduct.subproduct.version' # arbitrary string
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
        MainWindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VirtualTA"))
        self.Button_sent.setText(_translate("MainWindow", "Sent"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    #MainWindow.show()
    sys.exit(app.exec_())
